$beginningOfLogging = "2014/12/01" # start date of logging
$domain = "example.com" # domain
$exclude = "nobody" # exclude these users from statistics
$folder = "C:\path\" # files are stored under this directory
$nobody = "nobody" # wirte this when no user is connected
$remoteStore = "\\127.0.0.1\share\" # remote location to store the data additionally
$vcenter = "vcenter.example.com" # vcenter server to connect to
$virtualDisks = "C:\","D:\" # list of virtual volumes
$vmNamingScheme = "vdi*" # naming scheme used to filter for vdi vms
